Pages/DocenteHome/AggiungiMateria.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RipetizioniApp.Helpers;
using RipetizioniApp.Infrastructure;
using RipetizioniApp.Models;
using RipetizioniApp.ViewModels;

namespace RipetizioniApp.Pages.DocenteHome
{
    public record MateriaForm(string Nome);

    [Authorize(Roles = "Docente")]
    public class AggiungiMateriaModel(RipetizioniDbContext db) : PageModel
    {
        public string? Errore { get; private set; }
        public void OnGet(string errore)
        {
            Errore = errore;
        }

        public async Task<IActionResult> OnPost(MateriaForm form)
        {
            try
            {
                Materia materia = Materia.FromString(form.Nome);
                UtenteId id = User.Id;

                Docente docente = db.Docenti.Where((d) => d.Id == id).First();

                docente.Materie.Aggiungi(materia);

                await db.SaveChangesAsync();

                return Redirect(User.ProfiloURL);
            }
            catch (Exception err)
            {
                return Redirect($"/docenteHome/aggiungiMateria?errore={err.Message}");
            }
        }
    }
}

Pages/DocenteHome/ConfiguraSalario.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using RipetizioniApp.Helpers;
using RipetizioniApp.Infrastructure;
using RipetizioniApp.Models;
using RipetizioniApp.ViewModels;

namespace RipetizioniApp.Pages.DocenteHome
{

    public record ConfiguraSalarioForm(string Tipo, int? TariffaEuro, int? TariffaCentesimi)
    {
        private Moneta? Tariffa => 
            TariffaEuro != null && TariffaCentesimi != null 
            ? Moneta.FromInts(TariffaEuro.Value, TariffaCentesimi.Value) 
            : null;
        public CriterioRappresentation CriterioRappresentation => 
            new CriterioRappresentation(CriterioRappresentation.GetTypeFromString(Tipo), Tariffa);
    }
    
    [Authorize(Roles = "Docente")]
    public class ConfiguraSalarioModel(RipetizioniDbContext db) : PageModel
    {
        public string? Tipo = null;
        public void OnGet(string? tipo)
        {
            Tipo = tipo;
        }



        public async Task<ActionResult> OnPost(ConfiguraSalarioForm form)
        {
            CriterioPagamento criterio = form.CriterioRappresentation.ToDomainModel();
            UtenteId id = User.Id;
            Docente docente = await db.Docenti.Where((d)=>d.Id == id).FirstAsync();

            docente.ConfiguraCriterioPagamento(criterio);

            await db.SaveChangesAsync();

            return Redirect(User.ProfiloURL);
        }
    }
}

Pages/DocenteHome/Index.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RipetizioniApp.Pages.DocenteHome
{
    [Authorize(Roles = "Docente")]
    public class IndexModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/DocenteHome/Profilo.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using RipetizioniApp.Helpers;
using RipetizioniApp.Infrastructure;
using RipetizioniApp.Infrastructure.Entities;
using RipetizioniApp.Models;
using RipetizioniApp.Models.Sessioni;
using RipetizioniApp.ViewModels;

namespace RipetizioniApp.Pages.DocenteHome
{

    [Authorize]
    public class profiloModel(RipetizioniDbContext db) : PageModel
    {
        public Docente? Docente { get; private set;}

        public async Task OnGet(Guid idDocente)
        {
            Docente = await db.Docenti.Where((d)=>d.Id == new UtenteId(idDocente)).FirstAsync();
        }

        public async Task<IActionResult> OnGetEliminaMateria(string nomeMateria)
        {
            if(User.Ruolo != "Docente")
                return Forbid();

            var id = User.Id;
            Docente docente = await db.Docenti.Where((d)=> d.Id == id).FirstAsync();
            
            docente.Materie.RimuoviMateriaByNome(nomeMateria);

            await db.SaveChangesAsync();

            return Redirect(User.ProfiloURL);
        }

        public async Task<IActionResult> OnPostCreaSessione(Guid idDocente)
        {
            if(User.Ruolo != "Studente")
                return Forbid();
            
            UtenteId idStudente = User.Id;
            UtenteId idDocenteT = new UtenteId(idDocente);
            CriterioPagamento criterio = await db.Docenti
                                                    .Where((d)=>d.Id == idDocenteT)
                                                    .Select((d)=>d.CriterioPagamento)
                                                    .FirstAsync();
            
            Richiesta richiesta = criterio.CreaRichiesta(idDocenteT, idStudente);
            RichiestaEntity entity = richiesta.ToEntity();
            db.Add(entity);
            await db.SaveChangesAsync();

            return Redirect("/");
        }
    }
}

Pages/StudenteHome/Profilo.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RipetizioniApp.Pages.StudenteHome
{
    [Authorize(Roles = "Studente")]
    public class profiloModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/DocenteHome/AggiungiMateria.cshtml
@page
@model RipetizioniApp.Pages.DocenteHome.AggiungiMateriaModel
@{
}

<div class="form-container">
    <form action="" method="post">
        <h1>Aggiungi materia</h1>
        <p class="errore">@Model.Errore</p>
        <p>Nome: <input type="text" placeholder="Nome" name="Nome" required></p>
        <button>Aggiungi</button>
    </form>
</div>

Pages/DocenteHome/ConfiguraSalario.cshtml
@page
@model RipetizioniApp.Pages.DocenteHome.ConfiguraSalarioModel
@{
    
}

<div class="form-container">
    <form action="" method="post">
        <h1>Configura salario</h1>
        <p>Criterio pagamento: <select name="Tipo" asp-for="Tipo" onchange="window.location = '?tipo=' + this.value;">
            <option value="" selected disabled>Seleziona il criterio più adatto a te</option>
            <option value="CriterioNonImpostato">Nessun criterio</option>
            <option value="CriterioConcordare">Criterio da concordare</option>
            <option value="CriterioPagamentoMensile">Pagamento mensile</option>
            <option value="CriterioPagamentoOgniOra">Pagamento All'ora</option>
        </select></p>
        @if(Model.Tipo == "CriterioPagamentoMensile" || Model.Tipo == "CriterioPagamentoOgniOra"){
            <p>Tariffa: <input type="number" name="TariffaEuro" placeholder="Euro" required/> <input type="number" name="TariffaCentesimi" placeholder="Centesimi" required/></p>
        }
        <button>Configura</button>
    </form>
</div>

Pages/DocenteHome/Index.cshtml
@page
@model RipetizioniApp.Pages.DocenteHome.IndexModel
@{
}

<h1>Docente Page</h1>

Pages/DocenteHome/Profilo.cshtml
@page "/profiloDocente/{idDocente}"
@using RipetizioniApp.Helpers
@using RipetizioniApp.Models
@model RipetizioniApp.Pages.DocenteHome.profiloModel
@{
    Docente? docente = Model.Docente;
}


<div class="page">
    <div class="utente-banner">
        <div class="immagine-profilo-container">
            <img src="/img/user.png" alt="">
        </div>
        <div class="utente-info">
            <h1>@docente?.Credenziali.Username</h1>
            <p>@docente?.Generalita.Nome @docente?.Generalita.Cognome</p>
            <p>@docente?.Generalita.DataNascita</p>
        </div>
    </div>
    <div class="salario">
        <h1>Tariffa</h1>
        <div class="soldi-container">
            @await Html.PartialAsync("CriterioPagamentoView", docente?.CriterioPagamento)
            @if(User.Ruolo == "Docente"){
                <a href="/docenteHome/configuraSalario"><button>Configura</button></a>
            }
            @if(User.Ruolo == "Studente"){
                <form asp-page-handler="CreaSessione" method="post">
                    @await Html.PartialAsync("CreaSessioneButton", docente?.CriterioPagamento)
                </form>
            }
        </div>
    </div>
    <div class="dettagli-container">
        <div class="dettagli">
            <div class="dettagli-header">
                <h2>Materie</h2>
                @if(User.Ruolo == "Docente"){
                    <a href="/docenteHome/aggiungiMateria"><button>Aggiungi</button></a>
                }
            </div>
            <div class="lista">
                @foreach (Materia m in docente?.Materie ?? [])
                {
                    <div class="item">
                        <p>@m.Nome</p>
                        @if (User.Ruolo == "Docente")
                        {
                            <a href="?handler=EliminaMateria&nomeMateria=@m.Nome">Rimuovi</a>
                        }
                    </div>
                }
            </div>
        </div>
        <div class="dettagli">
            <h2>Pacchetti di risorse</h2>
            <div class="lista">
                <div class="item">
                    <p>Esami programmazione 1</p>
                </div>
                <div class="item">
                    <p>Esami Fondamenti</p>
                </div>
                <div class="item">
                    <p>Esercizi di programmazione</p>
                </div>
                <div class="item">
                    <p>Prova 4</p>
                </div>
            </div>
        </div>
    </div>
</div>